Study groups CRUD
NicFontana/lifeatde-api pull request #15
Opened 2018-09-13 12:56 UTC by NicFontana

* Implementate le operazioni di CRUD per i gruppi di studio
* Creato un SuccessSerializer per inviare messaggi di successo relativi a update e delete di risorse
* Fixato un metodo nel model Project
* Creato CourseSerializer

2018-09-14 15:01 UTC, FIAV1 requested changes

2018-09-14 15:01 UTC, FIAV1 commented on app/controllers/study_groups_controller.rb
> +      render json: ErrorSerializer.new(@study_group.errors, Rack::Utils.status_code(:unprocessable_entity)).serialized_json, status: :unprocessable_entity
```Rack::Utils``` da mettere negli include a inizio pagina

2018-09-14 15:01 UTC, FIAV1 commented on app/models/study_group.rb
> +	validates :title, presence: { message: "Questo campo non può essere vuoto." }
Togli i punti alla fine dei messaggi ty

2018-09-14 15:01 UTC, xBlue0 commented on app/serializers/success_serializer.rb
> +class SuccessSerializer
Secondo me vanno restituiti sempre i model/collection dell'oggetto in considerazione, mai un messaggio generico di ok

2018-09-14 15:33 UTC, NicFontana commented on app/controllers/study_groups_controller.rb
> +	  @serializer_options[:meta][:message] = 'Gruppo di studio eliminato con successo!'
@xBlue0 te l'ho piazzato comunque il messaggino 💋

2018-09-14 16:24 UTC, GiovanniFiorini commented on app/controllers/study_groups_controller.rb
> +	    if @study_group.update(study_group_params)
usiamo la sintassi unless-return? 
anche nella destroy

2018-09-14 16:24 UTC, GiovanniFiorini commented on app/models/project.rb
> +		where('projects.title LIKE ? OR projects.description LIKE ?', "%#{search}%", "%#{search}%")
da cancellare perchè sostituiata con lo scope nella mia pr

2018-09-14 16:24 UTC, GiovanniFiorini commented on app/serializers/study_group_serializer.rb
>  end
dato che course lo includi in ogni metodo perchè giustamente quando guardi un gruppo di studio devono esserci quelle info, ha senso fare il controllo if-loaded?, per me può andarsene perchè tanto li carichi sempre

2018-09-17 11:45 UTC, NicFontana commented on app/serializers/study_group_serializer.rb
>  end
Hai ragione, l'unico senso che ha è che se nei controller mi dimentico di fare l'include dei corsi, la response me lo fa notare perchè viene a mancare il dato, quindi so già qual'è il problema.
Al contrario serializzandono sempre il corso potrei avere il problema delle N+1 query senza accorgermene.

2018-09-17 12:49 UTC, merged