Auth
NicFontana/lifeatde-api pull request #25
Opened 2018-09-23 15:08 UTC by xBlue0

2018-09-24 13:26 UTC, GiovanniFiorini approved these changes

2018-09-24 14:20 UTC, NicFontana requested changes

2018-09-24 14:20 UTC, NicFontana commented on app/serializers/user_serializer.rb
> -  end
Questa robina ci serve però ihih!1!

2018-09-25 19:13 UTC, NicFontana approved these changes

2018-09-25 19:13 UTC, merged